default: &default
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5

development:
  <<: *default
  url: mysql2://root@127.0.0.1:3306/lunchimizer_development

test:
  <<: *default
  url: mysql2://root@127.0.0.1:3306/lunchimizer_test
